version: 2
updates:
  # Enable version updates for .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/agent"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/agent"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"